version: '3'

networks:
    shared:

services:
    postgres:
        image: postgres:12-alpine
        restart: unless-stopped
        tty: true
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: atlauncher-bot
            POSTGRES_USER: atlauncher-bot
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data/pgdat
            SERVICE_TAGS: dev
            SERVICE_NAME: postgres
        networks:
            - shared

volumes:
    postgres-data:
