version: 2

aliases:
    - &restore-cache
      keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # Fallback in case checksum fails
          - v1-dependencies-
    - &save-cache
      paths:
          - node_modules
      key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
    lint:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore-cache: *restore-cache
            - run: npm install
            - save-cache: *save-cache
            - run: npm run lint
    build:
        working_directory: ~/repo
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore-cache: *restore-cache
            - run: npm install
            - save-cache: *save-cache
            - run: npm run build

workflows:
    version: 2
    build:
        jobs:
            - lint
            - build
