name: Migration

on:
  push:
    branches:
      - master
    paths:
        - 'prisma/migrations/**'

jobs:
  migration:
    name: Run Migration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '16'
            check-latest: true

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Do Migration
        run: railway run npm run db:migrate:deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
